const LANGS = {
  en: { name: "English", native: "English", locale: "en-US" },
  zh: { name: "Chinese", native: "中文", locale: "zh-CN" },
  ja: { name: "Japanese", native: "日本語", locale: "ja-JP" },
  ko: { name: "Korean", native: "한국어", locale: "ko-KR" },
  fr: { name: "French", native: "Français", locale: "fr-FR" },
  de: { name: "German", native: "Deutsch", locale: "de-DE" },
  es: { name: "Spanish", native: "Español", locale: "es-ES" },
  vi: { name: "Vietnamese", native: "Tiếng Việt", locale: "vi-VN" }
};

export function supportedLanguages() {
  return Object.entries(LANGS).map(([code, item]) => ({ code, ...item }));
}

export function aiCapabilities() {
  return {
    contract_version: "1.0",
    provider: process.env.AI_PROVIDER || "demo",
    endpoint_ready: true,
    philosophy: "target-language-first",
    output_schema: {
      chunk: "string",
      plain_description: "string in target language only",
      usage: "string in target language only",
      examples: "array of contextual examples",
      related_chunks: "array",
      visual_concepts: "array",
      vocabulary: "array with target-language definitions",
      practice: "object",
      suggested_replies: "array",
      pronunciation: "string"
    }
  };
}

export async function analyzeSentence({ text, targetLanguage, user }) {
  // IMPORTANT ARCHITECTURE NOTE
  // This function is the ONLY provider boundary used by the UI.
  // Later replace demoAnalyze() with callOpenAI() without changing the frontend/database schema.
  // Keep the provider secret on the server. Never expose API keys to public/js.
  const provider = process.env.AI_PROVIDER || "demo";
  if (provider === "openai" && process.env.OPENAI_API_KEY) {
    // Reserved for ChatGPT/OpenAI integration.
    // return callOpenAI({ text, targetLanguage, user });
  }
  return demoAnalyze({ text, targetLanguage, user });
}

function demoAnalyze({ text, targetLanguage, user }) {
  const lang = LANGS[targetLanguage] || LANGS.en;
  const cleaned = String(text || "").trim().replace(/\s+/g, " ");
  const category = guessCategory(cleaned);
  const context = [user?.industry, user?.job_role].filter(Boolean).join(" · ");

  if (targetLanguage === "en") return englishChunkLesson(cleaned, category, context);

  return {
    provider: "demo",
    contract_version: "1.0",
    target_language: targetLanguage,
    target_language_name: lang.name,
    category,
    chunk: cleaned,
    pronunciation: "Pronunciation guide will be generated by the AI provider.",
    plain_description: `A concise ${lang.name}-only description will appear here. No native-language translation is required.`,
    usage: `Explain when, why and how this expression is used, entirely in ${lang.name}.`,
    image_key: imageKey(category),
    visual_concepts: ["situation", "people", "action", "result"],
    examples: [
      { text: cleaned, situation: category, image_key: imageKey(category) },
      { text: `A second natural example in ${lang.name}.`, situation: "Workplace", image_key: "project" },
      { text: `A third example adapted to ${context || "the learner's work"}.`, situation: "Your work", image_key: "feedback" }
    ],
    related_chunks: ["Related expression 1", "Related expression 2", "Related expression 3", "Related expression 4"],
    vocabulary: [
      { word: "Key word", definition: `Definition written only in ${lang.name}.`, image_key: "project" }
    ],
    suggested_replies: [`A natural reply in ${lang.name}.`, `A more concise reply in ${lang.name}.`],
    practice: {
      prompt: `Complete a sentence using this chunk in ${lang.name}.`,
      stem: cleaned,
      choices: ["before", "after", "while"],
      answer: "before"
    },
    thinking_prompt: `Describe the scene and intent directly in ${lang.name}; do not translate it into your native language.`
  };
}

function englishChunkLesson(text, category, context) {
  const chunk = chooseChunk(text);
  const normalized = polishEnglish(text || chunk);
  const data = {
    align: {
      chunk: "Let's align on this.",
      pronunciation: "/lets əˈlaɪn ɒn ðɪs/",
      plain_description: "Use this when you want everyone to share the same understanding before moving forward.",
      usage: "Common in meetings, project discussions and cross-team work. It sounds collaborative and action-oriented.",
      related: ["be on the same page", "get aligned", "make sure", "clarify", "confirm", "move forward", "set a clear direction", "take the next step"],
      replies: ["Absolutely. Let's confirm the goal and next steps.", "Sure. I'll summarize what we agreed on."],
      examples: [
        ["Let's align on this before we start development.", "Project kickoff", "meeting"],
        ["Let's align on the test plan and timeline.", "Manufacturing", "factory"],
        ["Let's align on the next steps and assign owners.", "Team meeting", "presentation"],
        ["Let's align on our expectations to avoid misunderstandings.", "1:1 discussion", "feedback"],
        ["Let's align on this and confirm by EOD.", "Email writing", "email"],
        ["Let's align on the key points from today's discussion.", "Summary", "project"]
      ]
    },
    priority: {
      chunk: "This is a high priority.",
      pronunciation: "/ðɪs ɪz ə haɪ praɪˈɒrəti/",
      plain_description: "Use this to signal that a task needs attention before less important work.",
      usage: "Useful when deadlines, customer impact or production risk require fast action.",
      related: ["please prioritize this", "top priority", "needs immediate attention", "time-sensitive", "urgent", "focus on this first"],
      replies: ["Understood. I'll prioritize it and keep you posted.", "Got it. I'll handle this first."],
      examples: [
        ["This is a high priority because production is blocked.", "Production issue", "factory"],
        ["Please treat this as a high-priority customer request.", "Customer request", "feedback"],
        ["This is our top priority for today's shift.", "Daily meeting", "meeting"]
      ]
    },
    update: {
      chunk: "Keep me posted.",
      pronunciation: "/kiːp miː ˈpəʊstɪd/",
      plain_description: "Use this when you want someone to continue sharing progress or new information with you.",
      usage: "Short, natural and common in spoken workplace English, chat and informal email.",
      related: ["keep me updated", "let me know", "send me an update", "share the latest status", "circle back", "follow up"],
      replies: ["Will do. I'll update you once I have more information.", "Sure. I'll keep you posted."],
      examples: [
        ["Keep me posted on the test result.", "Testing", "factory"],
        ["Keep me posted if the schedule changes.", "Planning", "project"],
        ["Please keep me posted on customer feedback.", "Customer", "feedback"]
      ]
    }
  };
  const key = /priority|urgent|deadline/i.test(text) ? "priority" : /update|posted|status/i.test(text) ? "update" : "align";
  const d = data[key];
  const examples = [...d.examples];
  if (normalized && !examples.some(([e]) => e.toLowerCase() === normalized.toLowerCase())) {
    examples.unshift([normalized, context || category, imageKey(category)]);
  }
  return {
    provider: "demo",
    contract_version: "1.0",
    target_language: "en",
    target_language_name: "English",
    category,
    chunk: d.chunk,
    pronunciation: d.pronunciation,
    plain_description: d.plain_description,
    usage: d.usage,
    image_key: imageKey(category),
    visual_concepts: ["shared goal", "discussion", "clear action", "result"],
    examples: examples.slice(0, 6).map(([t, situation, img]) => ({ text: t, situation, image_key: img })),
    related_chunks: d.related,
    vocabulary: vocabularyFor(key),
    suggested_replies: d.replies,
    practice: {
      prompt: "Complete the sentence using the chunk naturally.",
      stem: `${d.chunk.replace(/[.!?]$/, "")} ___ we proceed with the test.`,
      choices: ["before", "after", "because"],
      answer: "before"
    },
    thinking_prompt: "Look at the situation, name the intention in English, then choose the chunk. Avoid translating word by word."
  };
}

function vocabularyFor(key) {
  if (key === "priority") return [
    { word: "priority", definition: "something that should be dealt with before other things", image_key: "factory" },
    { word: "time-sensitive", definition: "needing action within a limited amount of time", image_key: "project" },
    { word: "blocked", definition: "unable to continue because something is preventing progress", image_key: "factory" }
  ];
  if (key === "update") return [
    { word: "posted", definition: "kept informed about what is happening", image_key: "email" },
    { word: "status", definition: "the current condition or progress of something", image_key: "project" },
    { word: "follow up", definition: "to continue checking or communicating after an earlier action", image_key: "feedback" }
  ];
  return [
    { word: "align", definition: "to bring people, goals or plans into agreement", image_key: "meeting" },
    { word: "clarify", definition: "to make an idea or situation easier to understand", image_key: "feedback" },
    { word: "confirm", definition: "to state that something is correct, agreed or definite", image_key: "email" },
    { word: "move forward", definition: "to continue to the next stage of a plan or process", image_key: "project" }
  ];
}

function chooseChunk(text) {
  if (/priority|urgent|deadline/i.test(text)) return "This is a high priority.";
  if (/update|posted|status/i.test(text)) return "Keep me posted.";
  return "Let's align on this.";
}
function polishEnglish(text) {
  const cleaned = String(text || "").trim();
  if (!cleaned) return "";
  const out = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  return /[.!?]$/.test(out) ? out : `${out}.`;
}
function guessCategory(text) {
  const t = String(text || "").toLowerCase();
  if (t.includes("meeting") || t.includes("align") || t.includes("discuss")) return "Meeting";
  if (t.includes("production") || t.includes("test") || t.includes("issue") || t.includes("station")) return "Manufacturing";
  if (t.includes("email") || t.includes("send") || t.includes("report")) return "Email";
  if (t.includes("deadline") || t.includes("priority") || t.includes("urgent")) return "Deadline";
  if (t.includes("feedback")) return "Feedback";
  return "Workplace";
}
function imageKey(category) {
  return ({ Meeting:"meeting", Manufacturing:"factory", Email:"email", Deadline:"project", Feedback:"feedback" })[category] || "project";
}
